// 호텔 체크인부터 체크아웃까지 쓰는 스페인어 9개.
//
// 체크인 → 시설 문의 → 문제 해결 → 체크아웃 순서. 숙소는 문제가 생겼을 때
// 말이 안 통하면 제일 곤란해서, No funciona 를 가운데 배치했다.

export default {
  id: 'hotel',
  title: '호텔에서 쓰는 스페인어',
  theme: 'hotel',
  cover: {
    eyebrow: '여행 스페인어',
    line1: '호텔에서',
    line2: '꼭 쓰는 표현',
    accentLine: '스페인어 9개',
    pill: '체크인부터 체크아웃까지',
  },
  caption: {
    headline: '🏨 호텔에서 쓰는 스페인어 9개',
    intro: [
      '체크인 한마디, 짐 맡기기, 그리고 뭔가 고장났을 때 🧳',
      '숙소는 말이 안 통하면 제일 곤란한 곳이라 이것만은 챙겨가세요 🥲',
    ],
    highlight: [
      '제일 요긴한 건 No funciona 예요 🔧',
      '샤워기든 에어컨이든 와이파이든, 안 되는 건 뭐든 이 한마디면 통해요!',
    ],
    hashtags: [
      '스페인여행', '스페인어', '여행스페인어', '스페인어공부', '스페인어회화',
      '왕초보스페인어', '스페인어독학', '유럽여행', '유럽여행준비', '여행준비물',
      '바르셀로나여행', '마드리드여행', '스페인호텔', '스페인어단어', '어학공부',
      '공부스타그램', 'DELE', '여행스타그램',
    ],
  },
  items: [
    {
      term: 'Tengo una reserva',
      pron: '뗑고 우나 레세르바',
      meaning: '예약했어요',
      tag: '체크인',
      emoji: '🛎️',
      example: 'Tengo una reserva a nombre de Kim.',
      exampleKo: '김으로 예약했어요.',
      tip: '체크인 첫 마디. 여권을 같이 내밀면 대부분 그대로 진행됩니다.',
    },
    {
      term: '¿A qué hora es el desayuno?',
      pron: '아 께 오라 에스 엘 데사유노',
      meaning: '조식 몇 시예요?',
      tag: '조식',
      emoji: '🥐',
      example: '¿A qué hora es el desayuno?',
      exampleKo: '조식은 몇 시부터예요?',
      tip: '조식 포함인지 물으려면 ¿El desayuno está incluido? 라고 하면 됩니다.',
    },
    {
      term: '¿Cuál es la contraseña del wifi?',
      pron: '꾸알 에스 라 꼰뜨라세냐 델 위피',
      meaning: '와이파이 비밀번호가 뭐예요?',
      tag: '와이파이',
      emoji: '📶',
      example: '¿Cuál es la contraseña del wifi?',
      exampleKo: '와이파이 비밀번호 알려주세요.',
      tip: '스페인에서는 wifi 를 "위피"에 가깝게 읽습니다. 알아듣기 어려운 이유예요.',
    },
    {
      term: '¿Hay aire acondicionado?',
      pron: '아이 아이레 아꼰디시오나도',
      meaning: '에어컨 있어요?',
      tag: '시설',
      emoji: '❄️',
      example: '¿Hay aire acondicionado en la habitación?',
      exampleKo: '객실에 에어컨 있어요?',
      tip: 'hay 는 ~이 있다. 뭐든 앞에 붙여서 있냐고 물어볼 수 있습니다.',
    },
    {
      term: 'No funciona',
      pron: '노 푼시오나',
      meaning: '고장났어요 / 안 돼요',
      tag: '문제',
      emoji: '🔧',
      example: 'La ducha no funciona.',
      exampleKo: '샤워기가 안 나와요.',
      tip: '안 되는 건 뭐든 이 한마디. 에어컨은 el aire, 열쇠는 la llave.',
    },
    {
      term: 'Una toalla más, por favor',
      pron: '우나 또아야 마스, 뽀르 파보르',
      meaning: '수건 하나 더 주세요',
      tag: '요청',
      emoji: '🧺',
      example: '¿Me trae una toalla más?',
      exampleKo: '수건 하나 더 갖다주시겠어요?',
      tip: 'más 만 붙이면 "하나 더"가 됩니다. 베개는 una almohada.',
    },
    {
      term: '¿Puedo dejar la maleta?',
      pron: '뿌에도 데하르 라 말레따',
      meaning: '짐 맡길 수 있어요?',
      tag: '짐',
      emoji: '🧳',
      example: '¿Puedo dejar la maleta aquí?',
      exampleKo: '여기 짐 좀 맡겨도 될까요?',
      tip: '체크아웃하고 저녁 비행기를 탈 때 반드시 쓰게 됩니다.',
    },
    {
      term: '¿Puede llamar a un taxi?',
      pron: '뿌에데 야마르 아 운 딱시',
      meaning: '택시 좀 불러주시겠어요?',
      tag: '부탁',
      emoji: '🚖',
      example: '¿Puede llamar a un taxi, por favor?',
      exampleKo: '택시 한 대 불러주시겠어요?',
      tip: '프런트에 하는 가장 흔한 부탁. ¿Puede...? 는 "해주실 수 있나요?"입니다.',
    },
    {
      term: 'Quiero hacer el check-out',
      pron: '끼에로 아세르 엘 체크아웃',
      meaning: '체크아웃할게요',
      tag: '체크아웃',
      emoji: '👋',
      example: 'Quiero hacer el check-out, por favor.',
      exampleKo: '체크아웃하려고요.',
      tip: '스페인 호텔도 check-in / check-out 은 영어 그대로 씁니다.',
    },
  ],
};
