// 숫자·요일·시간 9장.
//
// 전형적인 "저장형" 세트라 한 장에 여러 항목을 묶어 담는다. 표현 세트와 달리
// term 이 목록이지만, 레이아웃은 그대로 쓴다 (term → 음차 → 뜻 → 예문 → 팁).

export default {
  id: 'numbers',
  title: '숫자 · 요일 · 시간',
  theme: 'numbers',
  cover: {
    eyebrow: '왕초보 스페인어',
    line1: '저장해두고 쓰는',
    line2: '숫자 · 요일 · 시간',
    accentLine: '한 장 정리',
    pill: '가격 · 예약 · 약속에 매번 필요합니다',
  },
  caption: {
    headline: '🔢 스페인어 숫자 · 요일 · 시간 한 번에 정리',
    intro: [
      '가격 듣고, 예약하고, 약속 잡을 때 매번 필요한 것들 🗓️',
      '따로따로 찾기 귀찮으셨죠? 한 장씩 잘라서 담아뒀어요 📌',
    ],
    highlight: [
      '시간 말할 때만 규칙이 하나 있어요 ⏰',
      '1시만 Es la una, 나머지는 전부 Son las... 로 시작해요!',
    ],
    hashtags: [
      '스페인어', '스페인어공부', '왕초보스페인어', '스페인어독학', '스페인어단어',
      '스페인어숫자', '스페인어회화', '스페인어기초', '어학공부', '외국어공부',
      '공부스타그램', '스페인여행', '여행스페인어', 'DELE', '델레',
      '스페인어초보', '언어공부', '스페인어시험',
    ],
  },
  items: [
    {
      term: 'uno · dos · tres',
      pron: '우노 · 도스 · 뜨레스',
      meaning: '1 · 2 · 3',
      tag: '숫자',
      emoji: '1️⃣',
      example: 'Tres, por favor.',
      exampleKo: '세 개 주세요.',
      tip: '남성 명사 앞에서는 uno 가 un 으로 줄어듭니다 (un café).',
    },
    {
      term: 'cuatro · cinco · seis',
      pron: '꾸아뜨로 · 싱꼬 · 세이스',
      meaning: '4 · 5 · 6',
      tag: '숫자',
      emoji: '4️⃣',
      example: 'Una mesa para cuatro.',
      exampleKo: '네 명 자리요.',
      tip: 'c 는 e, i 앞에서만 "ㅅ" 소리가 납니다. cinco 가 "씽꼬"인 이유예요.',
    },
    {
      term: 'siete · ocho · nueve · diez',
      pron: '시에떼 · 오초 · 누에베 · 디에스',
      meaning: '7 · 8 · 9 · 10',
      tag: '숫자',
      emoji: '7️⃣',
      example: 'Son diez euros.',
      exampleKo: '10유로입니다.',
      tip: '가격은 대부분 euros 로 끝납니다. 숫자만 들으면 됩니다.',
    },
    {
      term: 'veinte · cincuenta · cien',
      pron: '베인떼 · 싱꾸엔따 · 시엔',
      meaning: '20 · 50 · 100',
      tag: '숫자',
      emoji: '💶',
      example: 'Cuesta veinte euros.',
      exampleKo: '20유로예요.',
      tip: '여행에서 실제로 듣는 큰 숫자는 이 셋이 대부분입니다.',
    },
    {
      term: 'lunes · martes · miércoles',
      pron: '루네스 · 마르떼스 · 미에르꼴레스',
      meaning: '월 · 화 · 수',
      tag: '요일',
      emoji: '📅',
      example: 'Nos vemos el lunes.',
      exampleKo: '월요일에 봐요.',
      tip: '요일 앞에는 el 을 붙입니다. el lunes = 이번 월요일에.',
    },
    {
      term: 'jueves · viernes',
      pron: '후에베스 · 비에르네스',
      meaning: '목 · 금',
      tag: '요일',
      emoji: '📅',
      example: 'El museo cierra el viernes.',
      exampleKo: '박물관은 금요일에 닫아요.',
      tip: '요일은 전부 소문자로 씁니다. 영어와 다른 점이에요.',
    },
    {
      term: 'sábado · domingo',
      pron: '사바도 · 도밍고',
      meaning: '토 · 일',
      tag: '요일',
      emoji: '🎉',
      example: 'El domingo está cerrado.',
      exampleKo: '일요일은 휴무예요.',
      tip: '스페인은 일요일에 문 닫는 가게가 많습니다. 일정 짤 때 꼭 확인하세요.',
    },
    {
      term: '¿Qué hora es?',
      pron: '께 오라 에스',
      meaning: '몇 시예요?',
      tag: '시간',
      emoji: '⏰',
      example: 'Perdón, ¿qué hora es?',
      exampleKo: '실례합니다, 몇 시예요?',
      tip: '스페인은 24시간제로 말하는 경우가 많습니다 (las quince = 15시).',
    },
    {
      term: 'Son las tres',
      pron: '손 라스 뜨레스',
      meaning: '3시예요',
      tag: '시간',
      emoji: '🕒',
      example: 'Son las tres y media.',
      exampleKo: '3시 30분이에요.',
      tip: '1시만 Es la una. 나머지는 전부 Son las 로 시작합니다. y media 는 30분.',
    },
  ],
};
