// 발음 규칙 9개.
//
// term 은 글자, pron 은 그 글자가 내는 소리, meaning 은 흔한 오해를 바로잡는
// 한 줄이다. 표현 세트와 필드 의미가 조금 다르지만 레이아웃은 그대로 쓴다.

export default {
  id: 'pronunciation',
  title: '스페인어 발음 규칙',
  theme: 'pronunciation',
  cover: {
    eyebrow: '왕초보 스페인어',
    line1: '이 아홉 가지만 알면',
    line2: '스페인어는',
    accentLine: '읽는 대로 읽힌다',
    pill: '영어처럼 읽어서 틀리는 것들',
  },
  caption: {
    headline: '🗣️ 이것만 알면 스페인어는 읽는 대로 읽혀요',
    intro: [
      '스페인어는 영어랑 달라서 예외가 거의 없어요 🙌',
      '아래 아홉 가지만 알면 처음 보는 단어도 그냥 읽을 수 있어요!',
    ],
    highlight: [
      '제일 많이 틀리는 건 h 예요 🤫',
      'hola 는 "홀라"가 아니라 "올라". 스페인어 h 는 항상 묵음이에요!',
    ],
    hashtags: [
      '스페인어', '스페인어발음', '스페인어공부', '왕초보스페인어', '스페인어독학',
      '스페인어기초', '스페인어회화', '스페인어단어', '어학공부', '외국어공부',
      '공부스타그램', 'DELE', '델레', '스페인어초보', '언어공부',
      '스페인여행', '여행스페인어', '발음교정',
    ],
  },
  items: [
    {
      term: 'h',
      pron: '소리 없음',
      meaning: '언제나 묵음',
      tag: '묵음',
      emoji: '🤫',
      example: 'hola · hotel · hospital',
      exampleKo: '올라 · 오뗄 · 오스삐딸',
      tip: '스페인어에서 h 는 절대 소리나지 않습니다. 예외가 없어요.',
    },
    {
      term: 'll',
      pron: '야 · 예 · 요',
      meaning: 'ㄹㄹ 아니고 ㅑ 소리',
      tag: '자음',
      emoji: '🔤',
      example: 'llamar · lluvia · calle',
      exampleKo: '야마르(부르다) · 유비아(비) · 까예(거리)',
      tip: '지역에 따라 "쟈"에 가깝게도 들립니다. 둘 다 맞습니다.',
    },
    {
      term: 'ñ',
      pron: '냐 · 뇨',
      meaning: '니 소리가 붙는다',
      tag: '자음',
      emoji: '〰️',
      example: 'año · español · mañana',
      exampleKo: '아뇨(해) · 에스빠뇰(스페인어) · 마냐나(내일)',
      tip: 'ano 와 año 는 완전히 다른 단어입니다. 물결을 빼먹으면 곤란해져요.',
    },
    {
      term: 'j',
      pron: '거센 ㅎ',
      meaning: 'ㅈ 아니고 거센 ㅎ',
      tag: '자음',
      emoji: '💨',
      example: 'jamón · trabajo · hijo',
      exampleKo: '하몬(햄) · 뜨라바호(일) · 이호(아들)',
      tip: '가래 뱉듯 목 안쪽에서 내는 소리입니다. 한국어 ㅎ보다 셉니다.',
    },
    {
      term: 'g + e, i',
      pron: '헤 · 히',
      meaning: 'j 와 같은 소리',
      tag: '자음',
      emoji: '🔀',
      example: 'gente · gimnasio · Argentina',
      exampleKo: '헨떼(사람들) · 힘나시오(체육관) · 아르헨띠나',
      tip: 'a, o, u 앞에서는 그냥 "ㄱ" 입니다 (gato 가또).',
    },
    {
      term: 'z / c + e, i',
      pron: '스페인은 th, 중남미는 ㅅ',
      meaning: '스페인 th, 중남미 ㅅ',
      tag: '지역차',
      emoji: '🌍',
      example: 'gracias · cerveza · plaza',
      exampleKo: '그라시아스 · 세르베사(맥주) · 쁠라사(광장)',
      tip: '스페인 본토는 혀를 살짝 물어 영어 th 처럼 냅니다. 중남미는 그냥 ㅅ.',
    },
    {
      term: 'v',
      pron: 'ㅂ',
      meaning: 'b 와 거의 같은 소리',
      tag: '자음',
      emoji: '👄',
      example: 'vino · viajar · vivir',
      exampleKo: '비노(와인) · 비아하르(여행하다) · 비비르(살다)',
      tip: '윗니를 아랫입술에 대지 않습니다. b 와 v 를 구분하지 않아요.',
    },
    {
      term: 'r / rr',
      pron: '굴리는 ㄹ',
      meaning: '혀를 떠는 ㄹ',
      tag: '자음',
      emoji: '🌀',
      example: 'perro · rojo · pero',
      exampleKo: '뻬rr오(개) · rr오호(빨강) · 뻬로(그러나)',
      tip: 'perro(개)와 pero(그러나)는 r 하나 차이입니다. 안 굴려도 대개 통해요.',
    },
    {
      term: 'a e i o u',
      pron: '아 에 이 오 우',
      meaning: '언제나 다섯 소리뿐',
      tag: '모음',
      emoji: '🎯',
      example: 'casa · mesa · libro',
      exampleKo: '까사(집) · 메사(책상) · 리브로(책)',
      tip: '영어처럼 상황 따라 달라지지 않습니다. 스페인어가 쉬운 가장 큰 이유예요.',
    },
  ],
};
