// 식당·카페에서 쓰는 스페인어 9개.
//
// 여행 세트(1편)의 후속. 앉기 → 주문 → 요청 → 계산 순서로 배열해서,
// 실제 식사 흐름을 따라가며 읽히게 했다.

export default {
  id: 'restaurant',
  title: '식당·카페에서 쓰는 스페인어',
  theme: 'restaurant',
  cover: {
    eyebrow: '여행 스페인어',
    line1: '식당·카페에서',
    line2: '꼭 쓰는 표현',
    accentLine: '스페인어 9개',
    pill: '메뉴판부터 계산까지 이 순서대로',
  },
  caption: {
    headline: '🍽️ 식당·카페에서 쓰는 스페인어 9개',
    intro: [
      '스페인 식당에서 진짜 필요한 말은 이 정도예요 🥘',
      '자리 잡고 → 주문하고 → 계산하는 순서 그대로 담았어요 👌',
    ],
    highlight: [
      '제일 자주 쓰게 되는 건 La cuenta, por favor 예요 🫶',
      '스페인은 자리에서 계산하는 곳이 많아서, 손 들고 이 한마디면 끝나요!',
    ],
    hashtags: [
      '스페인여행', '스페인어', '여행스페인어', '스페인어공부', '스페인어회화',
      '왕초보스페인어', '스페인어독학', '스페인맛집', '유럽여행', '유럽여행준비',
      '바르셀로나여행', '마드리드여행', '스페인어단어', '어학공부', '공부스타그램',
      'DELE', '여행스타그램', '타파스',
    ],
  },
  items: [
    {
      term: 'Una mesa para dos',
      pron: '우나 메사 빠라 도스',
      meaning: '두 명 자리 주세요',
      tag: '입장',
      emoji: '🪑',
      example: '¿Tienen mesa para dos?',
      exampleKo: '두 명 자리 있어요?',
      tip: '숫자만 바꾸면 됩니다. 혼자면 para uno, 넷이면 para cuatro.',
    },
    {
      term: 'La carta, por favor',
      pron: '라 까르따, 뽀르 파보르',
      meaning: '메뉴판 주세요',
      tag: '주문',
      emoji: '📖',
      example: '¿Me trae la carta?',
      exampleKo: '메뉴판 좀 갖다주시겠어요?',
      tip: 'menú 는 보통 오늘의 세트를 뜻해서, 메뉴판은 la carta 라고 합니다.',
    },
    {
      term: '¿Qué me recomienda?',
      pron: '께 메 레꼬미엔다',
      meaning: '뭐가 맛있어요?',
      tag: '추천',
      emoji: '🤔',
      example: '¿Qué me recomienda de aquí?',
      exampleKo: '여기서 뭐가 맛있어요?',
      tip: '메뉴를 못 읽겠을 때 가장 안전한 탈출구입니다.',
    },
    {
      term: 'Un café con leche',
      pron: '운 까페 꼰 레체',
      meaning: '카페라테 한 잔',
      tag: '카페',
      emoji: '☕',
      example: 'Un café con leche, por favor.',
      exampleKo: '카페라테 한 잔 주세요.',
      tip: '스페인에서 가장 흔한 주문. 아메리카노는 café americano 입니다.',
    },
    {
      term: 'Sin hielo / Sin azúcar',
      pron: '신 이엘로 / 신 아수까르',
      meaning: '얼음 빼고 / 설탕 빼고',
      tag: '요청',
      emoji: '🧊',
      example: 'Un zumo sin hielo, por favor.',
      exampleKo: '얼음 없이 주스 하나 주세요.',
      tip: 'sin 은 ~없이, con 은 ~넣고. 이 둘이면 주문이 자유로워집니다.',
    },
    {
      term: 'Soy alérgico a...',
      pron: '소이 알레르히꼬 아',
      meaning: '~에 알레르기가 있어요',
      tag: '알레르기',
      emoji: '⚠️',
      example: 'Soy alérgico a los frutos secos.',
      exampleKo: '견과류 알레르기가 있어요.',
      tip: '여성은 alérgica. 안전과 직결되니 이 문장만은 꼭 외워두세요.',
    },
    {
      term: 'Está muy rico',
      pron: '에스따 무이 리꼬',
      meaning: '정말 맛있어요',
      tag: '칭찬',
      emoji: '😋',
      example: '¡Está muy rico, gracias!',
      exampleKo: '진짜 맛있어요, 감사합니다!',
      tip: 'rico 는 맛있다는 뜻으로도 씁니다. 한마디로 분위기가 좋아져요.',
    },
    {
      term: 'Para llevar',
      pron: '빠라 예바르',
      meaning: '포장이요',
      tag: '포장',
      emoji: '🥡',
      example: 'Para llevar, por favor.',
      exampleKo: '포장해 주세요.',
      tip: '반대는 para tomar aquí — 여기서 먹고 갈게요.',
    },
    {
      term: 'La cuenta, por favor',
      pron: '라 꾸엔따, 뽀르 파보르',
      meaning: '계산서 주세요',
      tag: '계산',
      emoji: '🧾',
      example: '¿Nos trae la cuenta?',
      exampleKo: '계산서 좀 주시겠어요?',
      tip: '스페인은 자리에서 계산하는 곳이 많습니다. 손 들고 이 한마디면 됩니다.',
    },
  ],
};
