// 쇼핑·계산할 때 쓰는 스페인어 9개.
//
// 구경 → 착용 → 가격 → 결제 순서. 여행 세트의 ¿Cuánto cuesta? 를 받아서
// 확장하는 구성이라 1편을 본 사람에게 이어지는 느낌을 준다.

export default {
  id: 'shopping',
  title: '쇼핑·계산할 때 쓰는 스페인어',
  theme: 'shopping',
  cover: {
    eyebrow: '여행 스페인어',
    line1: '쇼핑할 때',
    line2: '꼭 쓰는 표현',
    accentLine: '스페인어 9개',
    pill: '구경부터 계산까지 이 아홉 마디면 끝',
  },
  caption: {
    headline: '🛍️ 쇼핑·계산할 때 쓰는 스페인어 9개',
    intro: [
      '가게 들어가서 나올 때까지, 실제로 쓰는 말만 모았어요 💳',
      '점원이 말 걸어올 때 얼어붙지 않으려면 4번이 특히 중요해요 🥹',
    ],
    highlight: [
      '¿Cuánto cuesta? 와 ¿Cuánto es? 는 다릅니다 👀',
      '물건 하나 값은 cuesta, 다 해서 얼마인지는 es 예요!',
    ],
    hashtags: [
      '스페인여행', '스페인어', '여행스페인어', '스페인어공부', '스페인어회화',
      '왕초보스페인어', '스페인어독학', '유럽여행', '유럽여행준비', '여행준비물',
      '바르셀로나여행', '마드리드여행', '스페인쇼핑', '스페인어단어', '어학공부',
      '공부스타그램', 'DELE', '여행스타그램',
    ],
  },
  items: [
    {
      term: 'Solo estoy mirando',
      pron: '솔로 에스또이 미란도',
      meaning: '그냥 구경 중이에요',
      tag: '구경',
      emoji: '👀',
      example: 'Gracias, solo estoy mirando.',
      exampleKo: '감사합니다, 그냥 보는 중이에요.',
      tip: '점원이 다가올 때 쓰는 가장 무난한 대답입니다.',
    },
    {
      term: '¿Puedo probármelo?',
      pron: '뿌에도 쁘로바르멜로',
      meaning: '입어봐도 돼요?',
      tag: '피팅',
      emoji: '👕',
      example: '¿Puedo probármelo?',
      exampleKo: '이거 한번 입어봐도 될까요?',
      tip: '탈의실은 el probador. 어디냐고 물으면 ¿Dónde está el probador?',
    },
    {
      term: '¿Tiene otra talla?',
      pron: '띠에네 오뜨라 따야',
      meaning: '다른 사이즈 있어요?',
      tag: '사이즈',
      emoji: '📏',
      example: '¿Tiene una talla más grande?',
      exampleKo: '더 큰 사이즈 있어요?',
      tip: '옷 사이즈는 talla, 신발 사이즈는 número 를 씁니다.',
    },
    {
      term: '¿Cuánto es?',
      pron: '꾸안또 에스',
      meaning: '다 해서 얼마예요?',
      tag: '계산',
      emoji: '💰',
      example: '¿Cuánto es todo?',
      exampleKo: '전부 얼마예요?',
      tip: '물건 하나 값은 ¿Cuánto cuesta?, 합계는 ¿Cuánto es? 입니다.',
    },
    {
      term: 'Es un poco caro',
      pron: '에스 운 뽀꼬 까로',
      meaning: '좀 비싸네요',
      tag: '가격',
      emoji: '😬',
      example: 'Es un poco caro para mí.',
      exampleKo: '저한테는 좀 비싸네요.',
      tip: '흥정은 시장에서만 통합니다. 일반 상점은 정찰제예요.',
    },
    {
      term: '¿Está en rebajas?',
      pron: '에스따 엔 레바하스',
      meaning: '세일 중이에요?',
      tag: '세일',
      emoji: '🏷️',
      example: '¿Esto está en rebajas?',
      exampleKo: '이거 세일 상품이에요?',
      tip: 'rebajas 는 시즌 세일. 스페인은 1월과 7월이 가장 큽니다.',
    },
    {
      term: 'Me lo llevo',
      pron: '메 로 예보',
      meaning: '이걸로 할게요',
      tag: '결정',
      emoji: '🙆',
      example: 'Vale, me lo llevo.',
      exampleKo: '좋아요, 이걸로 할게요.',
      tip: '여성 명사면 me la llevo. vale 는 "오케이" 정도의 맞장구입니다.',
    },
    {
      term: '¿Puedo pagar con tarjeta?',
      pron: '뿌에도 빠가르 꼰 따르헤따',
      meaning: '카드로 계산돼요?',
      tag: '결제',
      emoji: '💳',
      example: '¿Puedo pagar con tarjeta?',
      exampleKo: '카드로 결제할 수 있어요?',
      tip: '현금은 en efectivo. 작은 가게는 현금만 받기도 합니다.',
    },
    {
      term: '¿Me da una bolsa?',
      pron: '메 다 우나 볼사',
      meaning: '봉투 하나 주시겠어요?',
      tag: '봉투',
      emoji: '🛒',
      example: '¿Me da una bolsa, por favor?',
      exampleKo: '봉투 하나 주시겠어요?',
      tip: '스페인은 봉투가 유료인 곳이 많습니다. 장바구니를 챙기면 좋아요.',
    },
  ],
};
