// 교통·길찾기에서 쓰는 스페인어 9개.
//
// 말하는 표현만 넣으면 정작 대답을 못 알아듣는다. 그래서 마지막 두 장은
// "돌아오는 대답"(derecha / todo recto)을 알아듣는 쪽으로 배치했다.

export default {
  id: 'transport',
  title: '교통·길찾기 스페인어',
  theme: 'transport',
  cover: {
    eyebrow: '여행 스페인어',
    line1: '길 찾고 이동할 때',
    line2: '꼭 쓰는 표현',
    accentLine: '스페인어 9개',
    pill: '묻는 법 + 돌아오는 대답까지',
  },
  caption: {
    headline: '🚉 교통·길찾기 스페인어 9개',
    intro: [
      '표는 어떻게 사고, 이 버스는 어디 가고, 얼마나 먼지 🚌',
      '묻는 말만 알면 반쪽이라, 돌아오는 대답까지 같이 넣었어요 🗺️',
    ],
    highlight: [
      '길을 물으면 십중팔구 이 대답이 돌아와요 👇',
      'a la derecha 오른쪽 / a la izquierda 왼쪽 / todo recto 쭉 직진',
    ],
    hashtags: [
      '스페인여행', '스페인어', '여행스페인어', '스페인어공부', '스페인어회화',
      '왕초보스페인어', '스페인어독학', '유럽여행', '유럽여행준비', '여행준비물',
      '바르셀로나여행', '마드리드여행', '스페인기차', '스페인어단어', '어학공부',
      '공부스타그램', 'DELE', '여행스타그램',
    ],
  },
  items: [
    {
      term: '¿Dónde está la estación?',
      pron: '돈데 에스따 라 에스따시온',
      meaning: '역이 어디예요?',
      tag: '위치',
      emoji: '🚉',
      example: '¿Dónde está la estación de metro?',
      exampleKo: '지하철역이 어디예요?',
      tip: '기차역은 estación de tren, 지하철역은 estación de metro 입니다.',
    },
    {
      term: 'Un billete para Madrid',
      pron: '운 비예떼 빠라 마드리드',
      meaning: '마드리드행 표 한 장',
      tag: '매표',
      emoji: '🎫',
      example: 'Un billete para Madrid, por favor.',
      exampleKo: '마드리드행 표 한 장 주세요.',
      tip: '왕복은 ida y vuelta, 편도는 solo ida 라고 덧붙이면 됩니다.',
    },
    {
      term: '¿A qué hora sale?',
      pron: '아 께 오라 살레',
      meaning: '몇 시에 출발해요?',
      tag: '시간',
      emoji: '🕐',
      example: '¿A qué hora sale el próximo tren?',
      exampleKo: '다음 기차는 몇 시에 출발해요?',
      tip: '도착은 llega. ¿A qué hora llega? 는 몇 시에 도착하냐는 뜻이에요.',
    },
    {
      term: '¿Este autobús va a...?',
      pron: '에스떼 아우또부스 바 아',
      meaning: '이 버스 ~에 가요?',
      tag: '버스',
      emoji: '🚌',
      example: '¿Este autobús va al centro?',
      exampleKo: '이 버스 시내에 가요?',
      tip: 'a + el 은 항상 al 로 붙습니다. al centro = 시내로.',
    },
    {
      term: '¿Cómo llego a...?',
      pron: '꼬모 예고 아',
      meaning: '~에 어떻게 가요?',
      tag: '길찾기',
      emoji: '🧭',
      example: '¿Cómo llego al aeropuerto?',
      exampleKo: '공항에 어떻게 가요?',
      tip: '위치를 묻는 ¿Dónde está...? 와 달리 가는 방법을 물을 때 씁니다.',
    },
    {
      term: '¿Está lejos?',
      pron: '에스따 레호스',
      meaning: '멀어요?',
      tag: '거리',
      emoji: '📍',
      example: '¿Está lejos de aquí?',
      exampleKo: '여기서 멀어요?',
      tip: '가까우면 cerca. ¿Está cerca? 는 가깝냐는 뜻입니다.',
    },
    {
      term: 'Voy a esta dirección',
      pron: '보이 아 에스따 디렉시온',
      meaning: '이 주소로 가주세요',
      tag: '택시',
      emoji: '🚕',
      example: 'Voy a esta dirección, por favor.',
      exampleKo: '이 주소로 가주세요.',
      tip: '지도를 보여주면서 이 한마디면 택시는 해결됩니다.',
    },
    {
      term: 'Pare aquí, por favor',
      pron: '빠레 아끼, 뽀르 파보르',
      meaning: '여기서 세워주세요',
      tag: '하차',
      emoji: '🛑',
      example: 'Pare aquí, por favor.',
      exampleKo: '여기서 세워주세요.',
      tip: '택시·버스 공통. 내릴 곳이 보이면 이렇게 말하면 됩니다.',
    },
    {
      term: 'A la derecha / izquierda',
      pron: '아 라 데레차 / 이스끼에르다',
      meaning: '오른쪽에 / 왼쪽에',
      tag: '대답',
      emoji: '↔️',
      example: 'Está a la derecha, todo recto.',
      exampleKo: '쭉 직진해서 오른쪽에 있어요.',
      tip: '길을 물으면 돌아오는 대답. todo recto 는 쭉 직진이라는 뜻입니다.',
    },
  ],
};
