// EN — Hotel Spanish, 9 phrases.
// 회화 표현이라 문제 은행에 없다. 영어 문구는 직접 작성.

export default {
  id: 'hotel',
  title: 'Hotel Spanish',
  theme: 'hotel',
  thumbnailHint: 'A Spanish balcony at dusk with warm lamp light, or a room key on a bedside table.',
  cover: {
    eyebrow: 'TRAVEL SPANISH',
    line1: 'At the hotel',
    line2: 'in Spain',
    accentLine: '9 phrases',
    pill: 'Check-in, problems, and check-out',
  },
  caption: {
    headline: '🏨 9 Spanish phrases for hotels',
    intro: [
      'Checking in, leaving your bags, and when something breaks 🧳',
      'The hotel is the worst place to be stuck without words 🥲',
    ],
    highlight: [
      'The handiest one by far is No funciona 🔧',
      'Shower, air con, wifi, key card — if it does not work, this covers it.',
    ],
    hashtags: [
      'learnspanish', 'spanishforbeginners', 'travelspanish', 'spanishphrases',
      'spanishvocabulary', 'spainTravel', 'traveltips', 'hoteltips',
      'languagelearning', 'studyspanish', 'spanish', 'basicspanish',
      'europetravel', 'barcelona', 'madrid', 'dele', 'languagestudy', 'solotravel',
    ],
  },
  items: [
    {
      term: 'Tengo una reserva',
      pron: 'TENG-goh OO-nah reh-SEHR-bah',
      meaning: 'I have a reservation',
      tag: 'check-in',
      emoji: '🛎️',
      example: 'Tengo una reserva a nombre de Kim.',
      exampleTrans: 'I have a reservation under the name Kim.',
      tip: 'Say this and hand over your passport. Check-in is basically done.',
    },
    {
      term: '¿A qué hora es el desayuno?',
      pron: 'ah keh OH-rah ess el deh-sah-YOO-noh',
      meaning: 'What time is breakfast?',
      tag: 'breakfast',
      emoji: '🥐',
      example: '¿A qué hora es el desayuno?',
      exampleTrans: 'What time is breakfast?',
      tip: 'To ask if it is included: ¿El desayuno está incluido?',
    },
    {
      term: '¿Cuál es la contraseña del wifi?',
      pron: 'kwal ess lah kohn-trah-SEH-nyah del WEE-fee',
      meaning: 'What is the wifi password?',
      tag: 'wifi',
      emoji: '📶',
      example: '¿Cuál es la contraseña del wifi?',
      exampleTrans: 'What is the wifi password?',
      tip: 'Spaniards say wifi closer to WEE-fee, which is why it sounds unfamiliar.',
    },
    {
      term: '¿Hay aire acondicionado?',
      pron: 'eye AI-reh ah-kohn-dee-syoh-NAH-doh',
      meaning: 'Is there air conditioning?',
      tag: 'facilities',
      emoji: '❄️',
      example: '¿Hay aire acondicionado en la habitación?',
      exampleTrans: 'Is there air conditioning in the room?',
      tip: 'hay means there is. Put it in front of anything to ask if it exists.',
    },
    {
      term: 'No funciona',
      pron: 'noh foonk-SYOH-nah',
      meaning: 'It is not working',
      tag: 'problem',
      emoji: '🔧',
      example: 'La ducha no funciona.',
      exampleTrans: 'The shower is not working.',
      tip: 'Covers everything. el aire for the air con, la llave for the key.',
    },
    {
      term: 'Una toalla más, por favor',
      pron: 'OO-nah toh-AH-yah mahs por fah-BOR',
      meaning: 'One more towel, please',
      tag: 'request',
      emoji: '🧺',
      example: '¿Me trae una toalla más?',
      exampleTrans: 'Could you bring me one more towel?',
      tip: 'Add más to ask for one more of anything. A pillow is una almohada.',
    },
    {
      term: '¿Puedo dejar la maleta?',
      pron: 'PWEH-doh deh-HAR lah mah-LEH-tah',
      meaning: 'Can I leave my suitcase?',
      tag: 'luggage',
      emoji: '🧳',
      example: '¿Puedo dejar la maleta aquí?',
      exampleTrans: 'Can I leave my suitcase here?',
      tip: 'Essential when you check out in the morning but fly at night.',
    },
    {
      term: '¿Puede llamar a un taxi?',
      pron: 'PWEH-deh yah-MAR ah oon TAHK-see',
      meaning: 'Could you call a taxi?',
      tag: 'favour',
      emoji: '🚖',
      example: '¿Puede llamar a un taxi, por favor?',
      exampleTrans: 'Could you call a taxi, please?',
      tip: '¿Puede...? is the polite way to ask someone to do something for you.',
    },
    {
      term: 'Quiero hacer el check-out',
      pron: 'KYEH-roh ah-SEHR el check-out',
      meaning: 'I would like to check out',
      tag: 'check-out',
      emoji: '👋',
      example: 'Quiero hacer el check-out, por favor.',
      exampleTrans: 'I would like to check out, please.',
      tip: 'Spanish hotels use the English words check-in and check-out too.',
    },
  ],
};
