// EN — Numbers, days and telling the time, 9 cards.
// 저장형 세트라 한 장에 여러 항목을 묶는다. term 이 목록이지만 레이아웃은 동일.

export default {
  id: 'numbers',
  title: 'Numbers, Days & Time',
  theme: 'numbers',
  thumbnailHint: 'A simple graphic clock face beside a calendar page. Keep it flat and geometric, not photographic.',
  cover: {
    eyebrow: 'SPANISH FOR BEGINNERS',
    line1: 'Numbers, days',
    line2: 'and telling time',
    accentLine: 'all in one place',
    pill: 'Save this before your trip',
  },
  caption: {
    headline: '🔢 Spanish numbers, days and time — all in one place',
    intro: [
      'Prices, bookings, opening hours — you need these constantly 🗓️',
      'Tired of looking them up one at a time? Save this instead 📌',
    ],
    highlight: [
      'Telling the time has exactly one rule ⏰',
      'Only one o\'clock is Es la una. Everything else starts with Son las...',
    ],
    hashtags: [
      'learnspanish', 'spanishforbeginners', 'spanishnumbers', 'spanishvocabulary',
      'spanishbasics', 'languagelearning', 'studyspanish', 'spanish', 'basicspanish',
      'spanishtips', 'travelspanish', 'spainTravel', 'spanishclass', 'polyglot',
      'languagestudy', 'vocabulary', 'dele', 'spanishlessons',
    ],
  },
  items: [
    {
      term: 'uno · dos · tres',
      pron: 'OO-noh · dohs · trehs',
      meaning: '1 · 2 · 3',
      tag: 'numbers',
      emoji: '1️⃣',
      example: 'Tres, por favor.',
      exampleTrans: 'Three, please.',
      tip: 'Before a masculine noun uno shortens to un — un café.',
    },
    {
      term: 'cuatro · cinco · seis',
      pron: 'KWAH-troh · SEEN-koh · seys',
      meaning: '4 · 5 · 6',
      tag: 'numbers',
      emoji: '4️⃣',
      example: 'Una mesa para cuatro.',
      exampleTrans: 'A table for four.',
      tip: 'c only softens before e and i. That is why cinco starts with an s sound.',
    },
    {
      term: 'siete · ocho · nueve · diez',
      pron: 'SYEH-teh · OH-choh · NWEH-beh · dyehs',
      meaning: '7 · 8 · 9 · 10',
      tag: 'numbers',
      emoji: '7️⃣',
      example: 'Son diez euros.',
      exampleTrans: 'That is ten euros.',
      tip: 'Prices almost always end in euros, so you only need the number.',
    },
    {
      term: 'veinte · cincuenta · cien',
      pron: 'BAYN-teh · seen-KWEN-tah · syen',
      meaning: '20 · 50 · 100',
      tag: 'numbers',
      emoji: '💶',
      example: 'Cuesta veinte euros.',
      exampleTrans: 'It costs twenty euros.',
      tip: 'These three cover most of the big numbers you will hear as a traveller.',
    },
    {
      term: 'lunes · martes · miércoles',
      pron: 'LOO-nehs · MAR-tehs · MYEHR-koh-lehs',
      meaning: 'Mon · Tue · Wed',
      tag: 'days',
      emoji: '📅',
      example: 'Nos vemos el lunes.',
      exampleTrans: 'See you on Monday.',
      tip: 'Use el in front: el lunes means on Monday.',
    },
    {
      term: 'jueves · viernes',
      pron: 'HWEH-behs · BYEHR-nehs',
      meaning: 'Thu · Fri',
      tag: 'days',
      emoji: '📅',
      example: 'El museo cierra el viernes.',
      exampleTrans: 'The museum closes on Friday.',
      tip: 'Days are never capitalised in Spanish — unlike English.',
    },
    {
      term: 'sábado · domingo',
      pron: 'SAH-bah-doh · doh-MEEN-goh',
      meaning: 'Sat · Sun',
      tag: 'days',
      emoji: '🎉',
      example: 'El domingo está cerrado.',
      exampleTrans: 'It is closed on Sunday.',
      tip: 'Plenty of shops in Spain shut on Sundays. Plan around it.',
    },
    {
      term: '¿Qué hora es?',
      pron: 'keh OH-rah ess',
      meaning: 'What time is it?',
      tag: 'time',
      emoji: '⏰',
      example: 'Perdón, ¿qué hora es?',
      exampleTrans: 'Excuse me, what time is it?',
      tip: 'Spain often uses the 24-hour clock — las quince means 3pm.',
    },
    {
      term: 'Son las tres',
      pron: 'sohn lahs trehs',
      meaning: 'It is three o\'clock',
      tag: 'time',
      emoji: '🕒',
      example: 'Son las tres y media.',
      exampleTrans: 'It is half past three.',
      tip: 'One o\'clock is the exception: Es la una. y media means half past.',
    },
  ],
};
