// EN — Spanish pronunciation rules, 9 cards.
//
// 다른 세트와 필드 의미가 조금 다르다. term 은 글자, pron 은 그 글자가 내는
// 소리, meaning 은 영어 화자가 흔히 하는 오해를 바로잡는 한 줄이다.
// meaning 은 짧게 유지해야 한다 — 두 줄이 되면 카드가 빡빡해진다.

export default {
  id: 'pronunciation',
  title: 'Spanish Pronunciation Rules',
  theme: 'pronunciation',
  thumbnailHint: 'Typographic rather than photographic — one huge letterform (n with tilde, or ll) as the hero shape.',
  cover: {
    eyebrow: 'SPANISH FOR BEGINNERS',
    line1: 'Learn these 9 rules',
    line2: 'and Spanish reads',
    accentLine: 'exactly as written',
    pill: 'The sounds English speakers get wrong',
  },
  caption: {
    headline: '🗣️ 9 rules and Spanish reads exactly as it is written',
    intro: [
      'Unlike English, Spanish spelling almost never lies 🙌',
      'Learn these nine and you can read a word you have never seen before!',
    ],
    highlight: [
      'The one everyone gets wrong is h 🤫',
      'hola is OH-lah, not HOH-lah. Spanish h is always silent — no exceptions.',
    ],
    hashtags: [
      'learnspanish', 'spanishpronunciation', 'spanishforbeginners', 'spanishtips',
      'spanishbasics', 'languagelearning', 'studyspanish', 'spanish', 'basicspanish',
      'pronunciation', 'accent', 'spanishclass', 'polyglot', 'languagestudy',
      'spanishlessons', 'travelspanish', 'dele', 'languagehacks',
    ],
  },
  items: [
    {
      term: 'h',
      pron: 'silent',
      meaning: 'Never pronounced',
      tag: 'silent',
      emoji: '🤫',
      example: 'hola · hotel · hospital',
      exampleTrans: 'OH-lah · oh-TEL · os-pee-TAL',
      tip: 'Spanish h makes no sound at all. There are no exceptions to this one.',
    },
    {
      term: 'll',
      pron: 'YAH · YEH · YOH',
      meaning: 'Sounds like y, not l',
      tag: 'consonant',
      emoji: '🔤',
      example: 'llamar · lluvia · calle',
      exampleTrans: 'yah-MAR (call) · YOO-byah (rain) · KAH-yeh (street)',
      tip: 'In some regions it leans towards a j sound. Both are correct.',
    },
    {
      term: 'ñ',
      pron: 'NY',
      meaning: 'Like the ny in canyon',
      tag: 'consonant',
      emoji: '〰️',
      example: 'año · español · mañana',
      exampleTrans: 'AH-nyoh (year) · es-pah-NYOL · mah-NYAH-nah (tomorrow)',
      tip: 'ano and año are entirely different words. Do not drop the tilde.',
    },
    {
      term: 'j',
      pron: 'harsh H',
      meaning: 'Not j — a throaty h',
      tag: 'consonant',
      emoji: '💨',
      example: 'jamón · trabajo · hijo',
      exampleTrans: 'hah-MOHN (ham) · trah-BAH-hoh (work) · EE-hoh (son)',
      tip: 'Made at the back of the throat, rougher than an English h.',
    },
    {
      term: 'g + e, i',
      pron: 'HEH · HEE',
      meaning: 'Same sound as j',
      tag: 'consonant',
      emoji: '🔀',
      example: 'gente · gimnasio · Argentina',
      exampleTrans: 'HEN-teh (people) · heem-NAH-syoh (gym) · ar-hen-TEE-nah',
      tip: 'Before a, o, u it is a normal hard g — gato is GAH-toh.',
    },
    {
      term: 'z / c + e, i',
      pron: 'TH in Spain, S elsewhere',
      meaning: 'Depends on the region',
      tag: 'regional',
      emoji: '🌍',
      example: 'gracias · cerveza · plaza',
      exampleTrans: 'GRAH-thyahs · thehr-BEH-thah (beer) · PLAH-thah (square)',
      tip: 'Spain uses a th sound. Latin America uses a plain s. Both are standard.',
    },
    {
      term: 'v',
      pron: 'B',
      meaning: 'Almost identical to b',
      tag: 'consonant',
      emoji: '👄',
      example: 'vino · viajar · vivir',
      exampleTrans: 'BEE-noh (wine) · byah-HAR (travel) · bee-BEER (live)',
      tip: 'Your top teeth never touch your lip. Spanish does not separate b and v.',
    },
    {
      term: 'r / rr',
      pron: 'rolled R',
      meaning: 'Trilled at the start and in rr',
      tag: 'consonant',
      emoji: '🌀',
      example: 'perro · rojo · pero',
      exampleTrans: 'PEH-rroh (dog) · RROH-hoh (red) · PEH-roh (but)',
      tip: 'perro (dog) and pero (but) differ by one r. You will still be understood.',
    },
    {
      term: 'a e i o u',
      pron: 'ah eh ee oh oo',
      meaning: 'Only ever five sounds',
      tag: 'vowels',
      emoji: '🎯',
      example: 'casa · mesa · libro',
      exampleTrans: 'KAH-sah (house) · MEH-sah (table) · LEE-broh (book)',
      tip: 'Unlike English, vowels never change depending on the word. This is the big win.',
    },
  ],
};
