// EN — Restaurant & café Spanish, 9 phrases.
// 회화 표현이라 문제 은행에 없다. 영어 문구는 직접 작성.
// 순서는 실제 식사 흐름(입장 → 주문 → 요청 → 계산)을 따른다.

export default {
  id: 'restaurant',
  title: 'Restaurant & Café Spanish',
  theme: 'restaurant',
  thumbnailHint: 'An overhead cafe table — a cortado, a glass of water, a napkin on warm stone.',
  cover: {
    eyebrow: 'TRAVEL SPANISH',
    line1: 'Ordering food',
    line2: 'in Spain',
    accentLine: '9 phrases',
    pill: 'From the menu to the bill, in order',
  },
  caption: {
    headline: '🍽️ 9 Spanish phrases for restaurants and cafés',
    intro: [
      'Everything you actually say in a Spanish restaurant 🥘',
      'In order: sit down → order → ask → pay 👌',
    ],
    highlight: [
      'The one you will use every single time is La cuenta, por favor 🫶',
      'In Spain you usually pay at the table, so this is how you finish a meal.',
    ],
    hashtags: [
      'learnspanish', 'spanishforbeginners', 'travelspanish', 'spanishphrases',
      'spanishvocabulary', 'spainTravel', 'spanishfood', 'tapas', 'languagelearning',
      'studyspanish', 'spanish', 'basicspanish', 'foodietravel', 'europetravel',
      'barcelona', 'madrid', 'dele', 'languagestudy',
    ],
  },
  items: [
    {
      term: 'Una mesa para dos',
      pron: 'OO-nah MEH-sah PAH-rah dohs',
      meaning: 'A table for two',
      tag: 'arriving',
      emoji: '🪑',
      example: '¿Tienen mesa para dos?',
      exampleTrans: 'Do you have a table for two?',
      tip: 'Just swap the number: para uno, para cuatro.',
    },
    {
      term: 'La carta, por favor',
      pron: 'lah KAR-tah por fah-BOR',
      meaning: 'The menu, please',
      tag: 'ordering',
      emoji: '📖',
      example: '¿Me trae la carta?',
      exampleTrans: 'Could you bring me the menu?',
      tip: 'Ask for la carta, not el menú — menú usually means the set lunch.',
    },
    {
      term: '¿Qué me recomienda?',
      pron: 'keh meh reh-koh-MYEN-dah',
      meaning: 'What do you recommend?',
      tag: 'advice',
      emoji: '🤔',
      example: '¿Qué me recomienda de aquí?',
      exampleTrans: 'What do you recommend here?',
      tip: 'The safest escape when you cannot read a single item on the menu.',
    },
    {
      term: 'Un café con leche',
      pron: 'oon kah-FEH kohn LEH-cheh',
      meaning: 'A coffee with milk',
      tag: 'café',
      emoji: '☕',
      example: 'Un café con leche, por favor.',
      exampleTrans: 'A coffee with milk, please.',
      tip: 'The default Spanish coffee order. Black coffee is un café solo.',
    },
    {
      term: 'Sin hielo / Sin azúcar',
      pron: 'seen YEH-loh / seen ah-SOO-kar',
      meaning: 'No ice / No sugar',
      tag: 'request',
      emoji: '🧊',
      example: 'Un zumo sin hielo, por favor.',
      exampleTrans: 'A juice with no ice, please.',
      tip: 'sin means without, con means with. Those two unlock every order.',
    },
    {
      term: 'Soy alérgico a...',
      pron: 'soy ah-LEHR-hee-koh ah',
      meaning: 'I am allergic to...',
      tag: 'allergy',
      emoji: '⚠️',
      example: 'Soy alérgico a los frutos secos.',
      exampleTrans: 'I am allergic to nuts.',
      tip: 'Women say alérgica. Worth memorising properly — it is a safety phrase.',
    },
    {
      term: 'Está muy rico',
      pron: 'es-TAH mwee REE-koh',
      meaning: 'This is delicious',
      tag: 'compliment',
      emoji: '😋',
      example: '¡Está muy rico, gracias!',
      exampleTrans: 'This is delicious, thank you!',
      tip: 'rico means tasty here, not rich. It changes the whole mood of a meal.',
    },
    {
      term: 'Para llevar',
      pron: 'PAH-rah yeh-BAR',
      meaning: 'To take away',
      tag: 'takeaway',
      emoji: '🥡',
      example: 'Para llevar, por favor.',
      exampleTrans: 'To take away, please.',
      tip: 'The opposite is para tomar aquí — to have it here.',
    },
    {
      term: 'La cuenta, por favor',
      pron: 'lah KWEN-tah por fah-BOR',
      meaning: 'The bill, please',
      tag: 'paying',
      emoji: '🧾',
      example: '¿Nos trae la cuenta?',
      exampleTrans: 'Could you bring us the bill?',
      tip: 'Nobody brings it unprompted in Spain. You have to ask.',
    },
  ],
};
