// EN — Shopping & paying, 9 phrases.
// 회화 표현이라 문제 은행에 없다. 영어 문구는 직접 작성.

export default {
  id: 'shopping',
  title: 'Shopping & Paying in Spanish',
  theme: 'shopping',
  thumbnailHint: 'A colourful market stall or a boutique clothes rail, background thrown out of focus.',
  cover: {
    eyebrow: 'TRAVEL SPANISH',
    line1: 'Shopping in Spain',
    line2: 'without freezing up',
    accentLine: '9 phrases',
    pill: 'From browsing to paying at the till',
  },
  caption: {
    headline: '🛍️ 9 Spanish phrases for shopping and paying',
    intro: [
      'Everything from walking in to walking out with the bag 💳',
      'Number 1 is the one that saves you when staff approach 🥹',
    ],
    highlight: [
      '¿Cuánto cuesta? and ¿Cuánto es? are not the same 👀',
      'cuesta asks the price of one item. es asks the total.',
    ],
    hashtags: [
      'learnspanish', 'spanishforbeginners', 'travelspanish', 'spanishphrases',
      'spanishvocabulary', 'spainTravel', 'shoppinginspain', 'languagelearning',
      'studyspanish', 'spanish', 'basicspanish', 'traveltips', 'europetravel',
      'barcelona', 'madrid', 'dele', 'languagestudy', 'polyglot',
    ],
  },
  items: [
    {
      term: 'Solo estoy mirando',
      pron: 'SOH-loh es-TOY mee-RAHN-doh',
      meaning: 'I am just looking',
      tag: 'browsing',
      emoji: '👀',
      example: 'Gracias, solo estoy mirando.',
      exampleTrans: 'Thanks, I am just looking.',
      tip: 'The polite way to wave off a shop assistant without being rude.',
    },
    {
      term: '¿Puedo probármelo?',
      pron: 'PWEH-doh proh-BAR-meh-loh',
      meaning: 'Can I try it on?',
      tag: 'fitting',
      emoji: '👕',
      example: '¿Puedo probármelo?',
      exampleTrans: 'Can I try this on?',
      tip: 'The fitting room is el probador — ¿Dónde está el probador?',
    },
    {
      term: '¿Tiene otra talla?',
      pron: 'TYEH-neh OH-trah TAH-yah',
      meaning: 'Do you have another size?',
      tag: 'size',
      emoji: '📏',
      example: '¿Tiene una talla más grande?',
      exampleTrans: 'Do you have a bigger size?',
      tip: 'talla is for clothes. For shoes ask for a número instead.',
    },
    {
      term: '¿Cuánto es?',
      pron: 'KWAN-toh ess',
      meaning: 'How much is it altogether?',
      tag: 'total',
      emoji: '💰',
      example: '¿Cuánto es todo?',
      exampleTrans: 'How much is everything?',
      tip: 'Use cuesta for one item, es for the total at the till.',
    },
    {
      term: 'Es un poco caro',
      pron: 'ess oon POH-koh KAH-roh',
      meaning: 'It is a bit expensive',
      tag: 'price',
      emoji: '😬',
      example: 'Es un poco caro para mí.',
      exampleTrans: 'It is a bit expensive for me.',
      tip: 'Haggling only works in markets. Shops in Spain are fixed price.',
    },
    {
      term: '¿Está en rebajas?',
      pron: 'es-TAH en reh-BAH-hahs',
      meaning: 'Is it on sale?',
      tag: 'sale',
      emoji: '🏷️',
      example: '¿Esto está en rebajas?',
      exampleTrans: 'Is this on sale?',
      tip: 'rebajas are the seasonal sales. In Spain they run in January and July.',
    },
    {
      term: 'Me lo llevo',
      pron: 'meh loh YEH-boh',
      meaning: 'I will take it',
      tag: 'deciding',
      emoji: '🙆',
      example: 'Vale, me lo llevo.',
      exampleTrans: 'Okay, I will take it.',
      tip: 'For a feminine noun it becomes me la llevo. vale means okay.',
    },
    {
      term: '¿Puedo pagar con tarjeta?',
      pron: 'PWEH-doh pah-GAR kohn tar-HEH-tah',
      meaning: 'Can I pay by card?',
      tag: 'payment',
      emoji: '💳',
      example: '¿Puedo pagar con tarjeta?',
      exampleTrans: 'Can I pay by card?',
      tip: 'Cash is en efectivo. Small shops are sometimes cash only.',
    },
    {
      term: '¿Me da una bolsa?',
      pron: 'meh dah OO-nah BOHL-sah',
      meaning: 'Could I have a bag?',
      tag: 'bag',
      emoji: '🛒',
      example: '¿Me da una bolsa, por favor?',
      exampleTrans: 'Could I have a bag, please?',
      tip: 'Bags are usually not free in Spain. Bring your own if you can.',
    },
  ],
};
