// EN — Introducing yourself and keeping a conversation alive, 9 phrases.
//
// 회화 표현이라 문제 은행에 없다. 영어 문구는 직접 작성.
// 마지막 세 장은 "대화가 막혔을 때 빠져나오는 문장"이다. 초보가 실제로
// 가장 많이 필요로 하는 건 말을 거는 문장이 아니라 못 알아들었을 때의 문장이다.

export default {
  id: 'smalltalk',
  title: 'Introducing Yourself',
  theme: 'smalltalk',
  thumbnailHint: 'Two people mid-conversation at a cafe table, faces deliberately out of focus.',
  cover: {
    eyebrow: 'SPANISH FOR BEGINNERS',
    line1: 'Introduce yourself',
    line2: 'and survive',
    accentLine: 'the reply',
    pill: 'Including what to say when you get lost',
  },
  caption: {
    headline: '💬 9 Spanish phrases to introduce yourself (and survive the answer)',
    intro: [
      'Starting a conversation is easy. Understanding the reply is the hard part 🥲',
      'So the last three cards are your escape hatches 🛟',
    ],
    highlight: [
      'The single most useful phrase here is Más despacio, por favor 🐢',
      'Nobody minds slowing down. They just do not know they need to.',
    ],
    hashtags: [
      'learnspanish', 'spanishforbeginners', 'spanishconversation', 'spanishphrases',
      'spanishvocabulary', 'languagelearning', 'studyspanish', 'spanish',
      'basicspanish', 'spanishtips', 'speakspanish', 'spanishclass', 'polyglot',
      'languagestudy', 'travelspanish', 'spainTravel', 'dele', 'languageexchange',
    ],
  },
  items: [
    {
      term: 'Me llamo...',
      pron: 'meh YAH-moh',
      meaning: 'My name is...',
      tag: 'intro',
      emoji: '🙋',
      example: 'Hola, me llamo Jake.',
      exampleTrans: 'Hi, my name is Jake.',
      tip: 'Literally "I call myself". Soy Jake works too and is even shorter.',
    },
    {
      term: '¿Cómo te llamas?',
      pron: 'KOH-moh teh YAH-mahs',
      meaning: 'What is your name?',
      tag: 'asking',
      emoji: '❓',
      example: '¿Y tú? ¿Cómo te llamas?',
      exampleTrans: 'And you? What is your name?',
      tip: 'With strangers or older people, use the polite ¿Cómo se llama?',
    },
    {
      term: 'Mucho gusto',
      pron: 'MOO-choh GOOS-toh',
      meaning: 'Nice to meet you',
      tag: 'greeting',
      emoji: '🤝',
      example: 'Mucho gusto, María.',
      exampleTrans: 'Nice to meet you, María.',
      tip: 'Say it while shaking hands. Igualmente means "likewise".',
    },
    {
      term: '¿De dónde eres?',
      pron: 'deh DON-deh EH-rehs',
      meaning: 'Where are you from?',
      tag: 'asking',
      emoji: '🌍',
      example: '¿De dónde eres?',
      exampleTrans: 'Where are you from?',
      tip: 'The question you will be asked most as a traveller. Have your answer ready.',
    },
    {
      term: 'Soy de...',
      pron: 'soy deh',
      meaning: 'I am from...',
      tag: 'intro',
      emoji: '📍',
      example: 'Soy de Estados Unidos.',
      exampleTrans: 'I am from the United States.',
      tip: 'Just add your country. The UK is Reino Unido, Australia is Australia.',
    },
    {
      term: '¿Hablas inglés?',
      pron: 'AH-blahs een-GLEHS',
      meaning: 'Do you speak English?',
      tag: 'language',
      emoji: '🇬🇧',
      example: 'Perdón, ¿hablas inglés?',
      exampleTrans: 'Excuse me, do you speak English?',
      tip: 'Ask it in Spanish first. It changes how people respond to you.',
    },
    {
      term: 'No hablo mucho español',
      pron: 'noh AH-bloh MOO-choh es-pah-NYOL',
      meaning: 'I do not speak much Spanish',
      tag: 'escape',
      emoji: '😅',
      example: 'Lo siento, no hablo mucho español.',
      exampleTrans: 'Sorry, I do not speak much Spanish.',
      tip: 'Saying this in Spanish already proves it is not entirely true.',
    },
    {
      term: '¿Puede repetir?',
      pron: 'PWEH-deh reh-peh-TEER',
      meaning: 'Could you repeat that?',
      tag: 'escape',
      emoji: '🔁',
      example: 'Perdón, ¿puede repetir?',
      exampleTrans: 'Sorry, could you repeat that?',
      tip: 'Far more useful than pretending you understood. Use it freely.',
    },
    {
      term: 'Más despacio, por favor',
      pron: 'mahs des-PAH-syoh por fah-BOR',
      meaning: 'Slower, please',
      tag: 'escape',
      emoji: '🐢',
      example: 'Más despacio, por favor.',
      exampleTrans: 'Slower, please.',
      tip: 'The highest-value phrase on this list. Spaniards speak fast by default.',
    },
  ],
};
