// EN — Getting around, 9 phrases.
// 회화 표현이라 문제 은행에 없다. 영어 문구는 직접 작성.
// 마지막 카드는 "묻는 말"이 아니라 "돌아오는 대답"이다. 물어보기만 하고
// 대답을 못 알아들으면 아무 소용이 없기 때문.

export default {
  id: 'transport',
  title: 'Getting Around in Spanish',
  theme: 'transport',
  thumbnailHint: 'A narrow old-town alley leading toward bright light, or a train platform. No readable signage.',
  cover: {
    eyebrow: 'TRAVEL SPANISH',
    line1: 'Getting around',
    line2: 'and asking directions',
    accentLine: '9 phrases',
    pill: 'How to ask — and how to understand the answer',
  },
  caption: {
    headline: '🚉 9 Spanish phrases for trains, buses and directions',
    intro: [
      'Buying tickets, finding platforms, asking how far it is 🚌',
      'Knowing how to ask is only half of it — so the last card is the reply 🗺️',
    ],
    highlight: [
      'When you ask for directions, this is what comes back 👇',
      'a la derecha = right, a la izquierda = left, todo recto = straight ahead.',
    ],
    hashtags: [
      'learnspanish', 'spanishforbeginners', 'travelspanish', 'spanishphrases',
      'spanishvocabulary', 'spainTravel', 'traveltips', 'languagelearning',
      'studyspanish', 'spanish', 'basicspanish', 'europetravel', 'interrail',
      'barcelona', 'madrid', 'dele', 'languagestudy', 'backpacking',
    ],
  },
  items: [
    {
      term: '¿Dónde está la estación?',
      pron: 'DON-deh es-TAH lah es-tah-SYON',
      meaning: 'Where is the station?',
      tag: 'location',
      emoji: '🚉',
      example: '¿Dónde está la estación de metro?',
      exampleTrans: 'Where is the metro station?',
      tip: 'estación de tren for trains, estación de metro for the underground.',
    },
    {
      term: 'Un billete para Madrid',
      pron: 'oon bee-YEH-teh PAH-rah mah-DREED',
      meaning: 'One ticket to Madrid',
      tag: 'tickets',
      emoji: '🎫',
      example: 'Un billete para Madrid, por favor.',
      exampleTrans: 'One ticket to Madrid, please.',
      tip: 'Add ida y vuelta for a return, solo ida for one way.',
    },
    {
      term: '¿A qué hora sale?',
      pron: 'ah keh OH-rah SAH-leh',
      meaning: 'What time does it leave?',
      tag: 'timing',
      emoji: '🕐',
      example: '¿A qué hora sale el próximo tren?',
      exampleTrans: 'What time does the next train leave?',
      tip: 'llega is arrives. ¿A qué hora llega? asks the arrival time.',
    },
    {
      term: '¿Este autobús va a...?',
      pron: 'ES-teh ow-toh-BOOS bah ah',
      meaning: 'Does this bus go to...?',
      tag: 'bus',
      emoji: '🚌',
      example: '¿Este autobús va al centro?',
      exampleTrans: 'Does this bus go to the centre?',
      tip: 'a + el always contracts to al. So al centro, not a el centro.',
    },
    {
      term: '¿Cómo llego a...?',
      pron: 'KOH-moh YEH-goh ah',
      meaning: 'How do I get to...?',
      tag: 'directions',
      emoji: '🧭',
      example: '¿Cómo llego al aeropuerto?',
      exampleTrans: 'How do I get to the airport?',
      tip: 'Use this for the route. ¿Dónde está...? only asks where it is.',
    },
    {
      term: '¿Está lejos?',
      pron: 'es-TAH LEH-hohs',
      meaning: 'Is it far?',
      tag: 'distance',
      emoji: '📍',
      example: '¿Está lejos de aquí?',
      exampleTrans: 'Is it far from here?',
      tip: 'The opposite is cerca. ¿Está cerca? means is it nearby?',
    },
    {
      term: 'Voy a esta dirección',
      pron: 'boy ah ES-tah dee-rek-SYON',
      meaning: 'I am going to this address',
      tag: 'taxi',
      emoji: '🚕',
      example: 'Voy a esta dirección, por favor.',
      exampleTrans: 'I am going to this address, please.',
      tip: 'Show the address on your phone as you say it. Taxis solved.',
    },
    {
      term: 'Pare aquí, por favor',
      pron: 'PAH-reh ah-KEE por fah-BOR',
      meaning: 'Stop here, please',
      tag: 'getting off',
      emoji: '🛑',
      example: 'Pare aquí, por favor.',
      exampleTrans: 'Stop here, please.',
      tip: 'Works for taxis and buses alike.',
    },
    {
      term: 'A la derecha / izquierda',
      pron: 'ah lah deh-REH-chah / ees-KYEHR-dah',
      meaning: 'On the right / on the left',
      tag: 'the reply',
      emoji: '↔️',
      example: 'Está a la derecha, todo recto.',
      exampleTrans: 'It is straight ahead, on the right.',
      tip: 'This is what you will hear back. todo recto means straight ahead.',
    },
  ],
};
